---
- name: install Apache and Upload my WebPage
  hosts: all
  become: yes

  vars:
    source_file: ./MyWebSite/index.html
    destin_file: /var/www/html



  tasks:

  - name: Install Apache
    yum: name=httpd state=latest

  - name: Copy MyHomePage to Servers
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache

  - name: Start WebServer and enable
    service: name=httpd state=started enabled=yes




  handlers:

  - name: Restart Apache
    service: name=httpd state=restarted
         
