---
- name: My Playbook for variables
  hosts: all
  become: yes

  vars:
    message1: Privet
    message2: World
    secret:   ABV

  tasks:
  
  - name: Print Secret VARS
    debug:
      var: secret

  - debug:
      msg: "Sekretnoe Slovo: {{ secret }}"


  - debug:
      msg: "Vladelec etogo servera -->{{ owner }}<--"

  - set_fact: full_message="{{ message1 }} {{ message2 }} from {{ owner }}"

  - debug:
      var: full_message
   
  - debug:
      var: ansible_distribution
 
  - shell: uptime
    register: results

  - debug:
      var: results.stdout
